## Basics in Python 1

This python tutorial is a part of the EMBL Bioimage Analysis Tutorial by Toby Hodges.
If you are interested in taking his full introduction to python course, follow this link: https://git.embl.de/grp-bio-it-workshops/image-analysis-with-python/-/blob/master/session-1/Lecture_1_student.ipynb

#### 此筆記本的建議使用方式/ Advice on how to go through this notebook

我建議你打開另一個 Jupyter Notebook, 並將這裡的內容一行一行的寫到該 Notebook.執行時試著了解你所使用的函數的功能以及它運作的原理

#### Aim 1: Learn most basic syntax

- use of variables
- input, output
- conditional statements
- lists


In [1]:
print("Python is fun")

Python is fun


In [2]:
a = 4
b = "5"
c = a + 7

In [3]:
print(c)

11


Expect an error when running the following code. a is an integer and b is a string so they can not be added together.

In [4]:
d=a+b

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [5]:
d=a+int(b)
print(d)

9


In [6]:
d=str(a)+b
print(d)

45


In [7]:
for e in range (1,10):
    print(e)

1
2
3
4
5
6
7
8
9


In [8]:
the_earth_is_flat=True

In [9]:
if the_earth_is_flat:
    print("Take care not to fall off")

Take care not to fall off


In [10]:
# just testing division
print(5500/30)


183.33333333333334


In [11]:
f=[]
f.append(1)
f.append(2)
print(f)

e=[1,2,3]
print(e)


[1, 2]
[1, 2, 3]


In [12]:
## Marvelous chatbot

name = str(input("What is your name?"))
print("Nice to meet you ", name)

time = int(input("How many years have you been at EMBL?"))

if time<2:
    print('Welcome to EMBL')
elif time<10:
    print('That is a long time! You should have learnt Python sooner.')
else:
    print('Congrats for conquering the 9-year rule!')

What is your name?Kou
Nice to meet you  Kou
How many years have you been at EMBL?1
Welcome to EMBL


## Excercise 1:

from:
https://www.practicepython.org/solution/2014/02/26/03-list-less-than-ten-solutions.html
    
Take a list, say for example this one:

	a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

and write a program that prints out all the elements of the list that are less than 5.

Extras:

Instead of printing the elements one by one, make a new list that has all the elements less than 5 from this list in it and print out this new list.

Ask the user for a number and return a list that contains only elements from the original list a that are smaller than that number given by the user.



### Solution 1:

#### Further reading: 

Please find a lot of excercises in:
    
https://wiki.python.org/moin/BeginnersGuide

## Basics in Python 2

#### Aim 2: Numpy

- What is an array?
- Define and use arrays.




#### Create arrays using NumPy

The first thing to do is to import the library:


In [13]:
import numpy as np

In NumPy, arrays are lists, except that all the entries have to be of the same data type (int8, int32, float, boolean, etc).

Creating NumPy arrays is done using the same syntax as for a regular Python list andn in addition, using the NumPy function array as illustrated below. This function converts a list into a one-dimensional array, a list of lists in to a two-dimensional array, a list of list that is a list of lists into a three-dimensional array, etc. The class of such objects is numpy.ndarray:


In [14]:
# defining arrays
row = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 

# a row vector, also called a 1x9 array

print(row)

[1 2 3 4 5 6 7 8 9]


In [15]:
print(row.shape)
print(type(row))
print(row.dtype)

(9,)
<class 'numpy.ndarray'>
int32


In [16]:
# display the results
print ('row:\n', row, '\n has', len(row.shape), 'dimension(s) ;', 'is an object of class', type(row), '; with data type', row.dtype, '\n')


row:
 [1 2 3 4 5 6 7 8 9] 
 has 1 dimension(s) ; is an object of class <class 'numpy.ndarray'> ; with data type int32 



In [17]:
# defining arrays
col = np.array([[5],  # a column vector, also called a 9x1 array
                [6], 
                [3], 
                [-1], 
                [6], 
                [9], 
                [2],
                [5],
                [5]])

# display the results
print ('col:\n', col, '\nhas', len(col.shape), 'dimension(s) ;', 'is an object of class', type(col), '; with data type', col.dtype, '\n')

col:
 [[ 5]
 [ 6]
 [ 3]
 [-1]
 [ 6]
 [ 9]
 [ 2]
 [ 5]
 [ 5]] 
has 2 dimension(s) ; is an object of class <class 'numpy.ndarray'> ; with data type int32 



In [18]:
mat = np.array([[1, 2, 3, 4, -1, -2, -3, -4], [5, 6, 7, 8, -5, -6, -7, -8]]) # a 2x8 matrix or array

# display the results
print ('mat:\n', mat, '\nhas', len(mat.shape), 'dimension(s) ;', 'is an object of class', type(mat), '; with data type', mat.dtype, '\n')

mat:
 [[ 1  2  3  4 -1 -2 -3 -4]
 [ 5  6  7  8 -5 -6 -7 -8]] 
has 2 dimension(s) ; is an object of class <class 'numpy.ndarray'> ; with data type int32 



In [19]:
A = np.random.randint(0,high=100,size=(10,10),dtype=np.uint8)
print(A)

[[44 77 44 56 30  2 28  0 45 76]
 [13 88 64 77 67 28 25 44 80 75]
 [ 1 25 26  9 79 53 85 12 17 26]
 [81 48 79 24 21 36 13 32 32 62]
 [11 74 42 16 53 66 61 76 87 78]
 [11 71 99 66  5 23 35 80 26 27]
 [ 7 68 74 43 97 72 48 20 33 65]
 [99 15 51 98 97 86 34 15 47 90]
 [ 9 51 17  9 90 25 55 39  8 25]
 [16 60  6 22 76 33 81 56 30 55]]


In [20]:
B=np.zeros(A.shape,dtype=np.uint8)
print(B)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [21]:
B[:,3]=A[:,5]
print(B)

[[ 0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0 28  0  0  0  0  0  0]
 [ 0  0  0 53  0  0  0  0  0  0]
 [ 0  0  0 36  0  0  0  0  0  0]
 [ 0  0  0 66  0  0  0  0  0  0]
 [ 0  0  0 23  0  0  0  0  0  0]
 [ 0  0  0 72  0  0  0  0  0  0]
 [ 0  0  0 86  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0  0  0]
 [ 0  0  0 33  0  0  0  0  0  0]]


In [22]:
B[2:6,5:9]=A[2:6,5:9]

In [23]:
A = np.random.randint(0,high=120,size=(10,10),dtype=np.uint8)
B = np.random.randint(0,high=90,size=(10,10),dtype=np.uint8)
C = A-B
print(A)
print(B)
print(C)

[[  1  55 116  12  61  86  68  39  34  17]
 [ 56  52  72  14  84  79  91  15  41  80]
 [111  37 106  40  75  61 108  45  63  64]
 [ 58 100  60  26  22  42  49  19  53  45]
 [ 83  27  86   8  97  37  53  78  63   0]
 [ 22  67  90  64  85  22  38 118  35 108]
 [102  50  24   1  69  97  65  49  92  69]
 [104  54  11  74  21 117  20  32  10  52]
 [110  61  66  37  99   1  27 111  44  95]
 [ 66   1 110  83  78  66  14   0  29  95]]
[[18 47 81 28 59 75 68  9 48 49]
 [63 86 87 46 38  7 41 47 17 78]
 [ 2 43 33 89 43 13 49 34 49 67]
 [ 7 31 42  0 88 21 62 61 86 53]
 [17 48 72 48 41 29  2 83 67 14]
 [ 5 24  3 64 21 59 45 78 57 77]
 [ 3 60 41  4 15 22 81 46 23 13]
 [34  8 89 72 42  9 26 54 13 43]
 [43 50  1 49 33 55 16 52 20  3]
 [84 17 37 36 49  6 17 48 77 86]]
[[239   8  35 240   2  11   0  30 242 224]
 [249 222 241 224  46  72  50 224  24   2]
 [109 250  73 207  32  48  59  11  14 253]
 [ 51  69  18  26 190  21 243 214 223 248]
 [ 66 235  14 216  56   8  51 251 252 242]
 [ 17  43  87   0  64 2

In [24]:
A16 = A.astype(np.int16)
B16 = B.astype(np.int16)
C16 = A16-B16
print(A16)
print(B16)
print(C16)

[[  1  55 116  12  61  86  68  39  34  17]
 [ 56  52  72  14  84  79  91  15  41  80]
 [111  37 106  40  75  61 108  45  63  64]
 [ 58 100  60  26  22  42  49  19  53  45]
 [ 83  27  86   8  97  37  53  78  63   0]
 [ 22  67  90  64  85  22  38 118  35 108]
 [102  50  24   1  69  97  65  49  92  69]
 [104  54  11  74  21 117  20  32  10  52]
 [110  61  66  37  99   1  27 111  44  95]
 [ 66   1 110  83  78  66  14   0  29  95]]
[[18 47 81 28 59 75 68  9 48 49]
 [63 86 87 46 38  7 41 47 17 78]
 [ 2 43 33 89 43 13 49 34 49 67]
 [ 7 31 42  0 88 21 62 61 86 53]
 [17 48 72 48 41 29  2 83 67 14]
 [ 5 24  3 64 21 59 45 78 57 77]
 [ 3 60 41  4 15 22 81 46 23 13]
 [34  8 89 72 42  9 26 54 13 43]
 [43 50  1 49 33 55 16 52 20  3]
 [84 17 37 36 49  6 17 48 77 86]]
[[-17   8  35 -16   2  11   0  30 -14 -32]
 [ -7 -34 -15 -32  46  72  50 -32  24   2]
 [109  -6  73 -49  32  48  59  11  14  -3]
 [ 51  69  18  26 -66  21 -13 -42 -33  -8]
 [ 66 -21  14 -40  56   8  51  -5  -4 -14]
 [ 17  43  87   0  64 -

### Excercise 2:

Make a three-dimensional array c with the size (3,10,10) in which plane 1 and two are equal to A and B respectively. A and B are 10x10 filled with random numbers between 0..100 and 0..255 respectively.

### Solution 2:

#### Further reading: 

Please find more details in:
https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples/

## Other usefull stuff:

#### Usefull guide to conda libary management

https://conda.io/docs/user-guide/tasks/manage-pkgs.html
    
#### Use C code

https://codeburst.io/jupyter-notebook-tricks-for-data-science-that-enhance-your-efficiency-95f98d3adee4

### Magic

Docs accessible with %lsmagic
    
    %%bash - run cell as bash
    %%timeit - time cell
    ? f - get docstring
    ?? f - get source
    %run nb.ipynb - line magic, runs notebook
    %pdb - run debbuger on cell evaluation
    %env ENV_VAR=3 - set enviornment variable in kernel

In [ ]:
%lsmagic

## Cheat sheet markdown

from:

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet


### Headers

# H1
## H2
### H3
#### H4
##### H5
###### H6

Emphasis, aka italics, with *asterisks* or _underscores_.

Strong emphasis, aka bold, with **asterisks** or __underscores__.

Combined emphasis with **asterisks and _underscores_**.

Strikethrough uses two tildes. ~~Scratch this.~~

1. First ordered list item
2. Another item
⋅⋅* Unordered sub-list. 
1. Actual numbers don't matter, just that it's a number
⋅⋅1. Ordered sub-list
4. And another item.

* Unordered list can use asterisks
- Or minuses
+ Or pluses


Colons can be used to align columns.

| Header    | Another header   |
|:---------:|:----------------:|
| field 1   | center align     |
| field 2   | something else   |

| Header   | Another header  |
|:---------|:----------------|
| field 1  |left allign      |
| field 2  |something else   |

There must be at least 3 dashes separating each header cell.
The outer pipes (|) are optional, and you don't need to make the 
raw Markdown line up prettily. You can also use inline Markdown.

Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3


Three or more...

---

Hyphens

### Line Break:

Hello  (<-- two spaces)
World

Hello  
World